name: Auto Convert Xray to Sing-Box (HY2)

on:
  schedule:
    # Запуск каждые 5 часов
    - cron: '0 */5 * * *'
  workflow_dispatch: # Ручной запуск

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests maxminddb

      - name: Run scripts
        run: |
          python Python/mobile-hy2.py
          python Python/mobile-vless-http.py
          python Python/mobile-trojan.py

      - name: Commit and push if changed
        run: |
          # 1. Настройка бота GitHub Actions
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # 2. Проверяем, создал ли Python-скрипт нужный файл
          if [ ! -f "sing-box-hy2.json" ]; then
            echo "❌ Ошибка: Файл sing-box-hy2.json не найден! Проверьте имя output_filename в Python/mobile-hy2.py"
            exit 1
          fi
          if [ ! -f "sing-box-vless-http.json" ]; then
            echo "❌ Ошибка: Файл sing-box-vless-http.json не найден! Проверьте имя output_filename в Python/mobile-vless-http.py"
            exit 1
          fi
          if [ ! -f "sing-box-trojan.json" ]; then
            echo "❌ Ошибка: Файл sing-box-torjan.json не найден! Проверьте имя output_filename в Python/mobile-trojan.py"
            exit 1
          fi

          # 3. Добавляем файл в индекс
          git add sing-box-hy2.json sing-box-vless-http.json sing-box-trojan.json
          git status
          
          # 4. Коммитим и пушим только при наличии изменений
          if git diff --cached --quiet; then
            echo "Нет изменений для коммита."
          else
            git commit -m "Auto-update sing-box-hy2.json & sing-box-vless-http.json & sing-box-torjan.json"
            git push
          fi
