name: Auto Convert Xray to Sing-Box vless-reality

on:
  schedule:
    # Запуск каждые 5 часов
    - cron: '0 */5 * * *'
  workflow_dispatch: # Ручной запуск

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests maxminddb

      - name: Run scripts
        run: |
          python python/vless_reality_tun.py
          python python/vless_reality_v2ray.py


      - name: Commit and push if changed
        run: |
          # 1. Настройка бота GitHub Actions
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 2. Добавляем файл в индекс
          git add vless_reality_tun.json vless_reality.txt
          git status
          
          # 3. Коммитим и пушим только при наличии изменений
          if git diff --cached --quiet; then
            echo "Нет изменений для коммита."
          else
            git commit -m "Auto-update vless_reality_tun.json & vless_reality.txt"
            git push
          fi

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.delete_old_workflows }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3
