name: Auto Convert Xray to Sing-Box Vless-gRPC

on:
  schedule:
    # Запуск каждые 5 часов
    - cron: '0 */5 * * *'
  workflow_dispatch: # Ручной запуск

jobs:
  convert:
    runs-on: ubuntu-latest
    
    # Права на запись оставляем, они необходимы для git push
    permissions:
      contents: write
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # Ошибочная строка кэша удалена

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests maxminddb

      - name: Run scripts
        run: |
          python python/vless_grpc_tun.py
          python python/vless_grpc_v2ray.py

      - name: Commit and push if changed
        run: |
          # Настройка бота GitHub Actions
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"

          # Добавляем файл в индекс
          git add vless_grpc_tun.json vless_grpc.txt
          
          # Коммитим и пушим только при наличии изменений
          if git diff --cached --quiet; then
            echo "Нет изменений для коммита."
          else
            git commit -m "Auto-update vless_grpc_tun.json & vless_grpc.txt"
            git push
          fi
